    <style>
        input,textarea,select{margin:15px;width:300px;}
        a{color:black;text-decoration:none}
    </style>
    <table>
        <tr>
            <td><a href="index.php"><h3>Home</h3></a>
            <td>||</td>
            <td><h4>Cadastrar:</h4></td>
            <td><a href="form_familia.php">Família </a>|</td>
            <td><a href="form_genero.php">Genêro </a>|</td>
            <td><a href="form_especie.php">Espécie </a></td>
            <td>||</td>
            <td><h4>Listar:</h4></td>
            <td><a href="listar_familia.php">Família </a>|</td>
            <td><a href="listar_genero.php">Genêro </a>|</td>
            <td><a href="listar_especie.php">Espécie </a></td>
        </tr>
    </table>
    <hr />
