<nav class="site-header sticky-top py-1 bg-light">
	<div class="container text-center">
		<a class="py-2 px-4 d-none d-md-inline-block text-decoration-none text-body" href="index.php">Home</a>
		<a class="py-2 px-4 d-none d-md-inline-block text-decoration-none text-body" href="form_agendamento.php">Agendar</a>
		<a class="py-2 px-4 d-none d-md-inline-block text-decoration-none text-body" href="lista_agendamento.php">Lista de Agendamentos</a>
	</div>
</nav>