    <style>
        input,textarea,select{margin:15px;width:300px;}
        a{color:black;text-decoration:none}
        body{font-family:sans-serif;background-color:white}
    </style>
    <table cellspacing="3px">
        <tr>
            <td><a href="index.php"><h3>Home</h3></a></td>
            <td></td>
            <td><h4>Cadastrar:</h4></td>
            <td><a href="form_familia.php">Família </a>|</td>
            <td><a href="form_genero.php">Genêro </a>|</td>
            <td><a href="form_especie.php">Espécie </a></td>
            <td></td>
            <td><h4>Listar:</h4></td>
            <td><a href="listar_familia.php">Família </a>|</td>
            <td><a href="listar_genero.php">Genêro </a>|</td>
            <td><a href="listar_especie.php">Espécie </a></td>
            <td></td>
            <td><h4>Acessibilidade:</h4></td>
            <td><button id="aumentaFonte">A+</button></td>
            <td><button id="fontePadrao">A</button></td>
            <td><button id="diminuiFonte">A-</button></td>
            <td><button id="altoContraste">Alto Contraste</button></td>
        </tr>
    </table>
    <hr />
