<article>
    <div class="container">
        <div class="table-responsive">
            <br/>
            <br/>
            <br/>
            <table class="table table-striped" border="1" cellpadding="8px" >
                <thead class="thead-dark">
                    <tr>
                        <th>Código</th> 
                        <th>Palavra</th>
                        <th>Dica</th>
                        <th>Dica Específica</th> 
                        <th>Dica Específica 2</th>
                        <th>Editar</th>
                        <th>Excluir</th>  
                    </tr>
                </thead>
                <tbody>
                    <?php exibe_palavra();?>
                </tbody>
            </table>
        </div>
    </div>
</article>