<article>
    <div class="container">
        <div class="table-responsive">
            <br/>
            <br/>
            <br/>
            <table class="table table-striped" border="1" cellpadding="8px" >
                <thead class="thead-dark">
                    <tr>
                        <th>Código</th> 
                        <th>Nome</th>
                        <th>E-mail</th>
                        <th>Pontuação</th> 
                        <th>Jogos Ganhos</th>
                        <th>Jogos Perdidos</th>
                        <th>Troféus</th>
                        <th>Editar</th>
                        <th>Excluir</th>  
                    </tr>
                </thead>
                <tbody>
                    <?php exibe_usuarios();?>
                </tbody>
            </table>
        </div>
    </div>
</article>