<article>
    <div class="container">
        <div class="table-responsive">
            <br/>
            <br/>
            <table class="table table-striped" border="1">
                <thead class="thead-dark">
                    <tr>
                        <th width="10px">Posição</th> 
                        <th>Nome</th>
                        <th>Pontuação</th> 
                        <th>Troféus</th> 
                    </tr>
                </thead>
                <tbody>
                    <?php exibe_ranking();?>
                </tbody>
            </table>
        </div>
    </div>
</article>