<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
      </div>
      <div class="modal-body">
        <h3 class="h3-modal">Você atingiu o limite de acessos mensal</h3>
      </div>
      <div class="modal-footer">
        <a href="#">Deseja tornar-se um assinante?</a>
        <a href="#">Já é assinante? Clique aqui para entrar</a>
      </div>
    </div>
  </div>
</div>